# Generated by Django 4.2.7 on 2023-12-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.CharField(max_length=2),
        ),
    ]
